name: Publish Package

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PUSH_TOKEN }}

      - name: Get the commit message
        id: commit_message
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          echo "Commit Message: $COMMIT_MESSAGE"
          echo "::set-output name=message::$COMMIT_MESSAGE"

      - name: Check commit message to see if it came from "npm patch"
        run: |
          if [[ "${{ steps.commit_message.outputs.message }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Skipping pipeline due to commit message matching version format"
            exit 0  # Exiting with 0 stops the pipeline here
          else
            echo "Commit message doesn't match version format. Proceeding with pipeline."
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Run bumpVersionIfNeeded.js script
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          node bumpVersionIfNeeded.js
        id: bump_version

      - name: Check if version was bumped and publish
        if: steps.bump_version.outcome == 'success'
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          npm publish --access public
          git push
